In [1]:
import numpy as np
import pandas as pd
import time

a = input('Enter range:').split()
a = list(map(int,a))
performance = pd.DataFrame(columns=['Numbers','Answer','Entered Answer','Time Taken'])


size = int(input('Enter Size:'))
begin_time = time.time()
It = int(input('Iterations:'))

print('----------------------------------------------------------------------')
print('----------------------------------------------------------------------')



for i in range(It):
    
    start_time = time.time()
    x = np.random.randint(a[0],a[1],size = size)
    print(i,')',x)

    ans = sum(x)

    entered = int(input('Enter the sum:'))

    
    if entered == ans:
        flag = 1
    else:
        flag = 0
        
        
    if flag == 1:
        print('Correct!')
        end_time = time.time()
        df= {'Numbers':x,'Answer':sum(x),'Entered Answer':ans,'Time Taken':(end_time-start_time)}
        performance = performance.append(df, ignore_index=True)
        print('Time Taken:',end_time-start_time,'secs') 
        print('----------------------------------------------------------------------')
        continue
        print('END')
        
        
    else:
        end_time = time.time()
        df= {'Numbers':x,'Answer':sum(x),'Entered Answer':ans,'Time Taken':(end_time-start_time)}
        performance = performance.append(df, ignore_index=True)
        print('over')
        print('Correct Ans is :',sum(x))
        break
        

end_ti = time.time()
print('Total time:',(end_ti-begin_time)/60,'mins')

import openpyxl
dt = list(time.localtime())
dt
da=str(dt[:3])
ti=str(dt[3:6])
dati = da+ti
filename = 'Addition'+dati+'.xlsx'


performance.to_excel(filename, index = False)

Enter range:0 100
Enter Size:2
Iterations:10
----------------------------------------------------------------------
----------------------------------------------------------------------
0 ) [63 81]
Enter the sum:144
Correct!
Time Taken: 9.007075786590576 secs
----------------------------------------------------------------------
1 ) [84 60]
Enter the sum:144
Correct!
Time Taken: 3.1334869861602783 secs
----------------------------------------------------------------------
2 ) [72 73]
Enter the sum:145
Correct!
Time Taken: 4.12343430519104 secs
----------------------------------------------------------------------
3 ) [99 68]
Enter the sum:167
Correct!
Time Taken: 9.091779470443726 secs
----------------------------------------------------------------------
4 ) [77  9]
Enter the sum:86
Correct!
Time Taken: 10.188892126083374 secs
----------------------------------------------------------------------
5 ) [89 68]
Enter the sum:157
Correct!
Time Taken: 7.763372898101807 secs
----------------------------------------------------------------------
6 ) [73 59]
Enter the sum:132
Correct!
Time Taken: 9.629075765609741 secs
----------------------------------------------------------------------
7 ) [60 96]
Enter the sum:156
Correct!
Time Taken: 7.320966720581055 secs
----------------------------------------------------------------------
8 ) [ 4 52]
Enter the sum:56
Correct!
Time Taken: 3.222801446914673 secs
----------------------------------------------------------------------
9 ) [93 93]
Enter the sum:186
Correct!
Time Taken: 4.5652124881744385 secs
----------------------------------------------------------------------
Total time: 1.1954272588094075 mins

In [49]:
import time
import openpyxl
dt = list(time.localtime())
dt
da=str(dt[:3])
ti=str(dt[3:6])
dati = da+ti
filename = 'Addition'+dati+'.xlsx'


performance.to_excel(filename, index = False)

In [50]:
filename

'Addition[2020, 8, 16][13, 1, 23].xlsx'

In [27]:
import time
dt = list(time.localtime())
x =str(dt).split()

In [3]:
performance

    Numbers Answer Entered Answer  Time Taken
0   [0, 94]     94             94    2.782899
1  [26, 77]    103            103   11.464063
2  [46, 51]     97             97    3.961794
3  [32, 33]     65             65    3.330894
4  [47, 91]    138            138    8.304399
5  [35, 56]     91             91    4.072277
6  [67, 14]     81             81    5.976046
7  [43, 83]    126            126    8.834594
8  [68, 12]     80             80    4.418396
9  [85, 72]    157            157    6.441003

In [6]:
sum(performance['Time Taken'])/60

0.9931060632069906